---
title: "Tutorial showcasing the cerUB package for R"
authors: "Andreas Angourakis"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
description: "This document shows how to use *cerUB* protocols to explore petrographic and compositional data. As an example, we provide the 'amphorae' dataset concerning wine Roman amphorae from sites in Catalonia, NE Spain."
url: 'https://andros-spica.github.io/cerUb_tutorial/'
github-repo: Andros-Spica/cerUb_tutorial
documentclass: book
always_allow_html: yes
urlcolor: blue
fontsize: 12pt
geometry: margin = 1.2in
params:
  ispdf: TRUE
---

```{r, echo = FALSE, message=FALSE, warning=FALSE}
library(knitr)
opts_chunk$set(collapse = TRUE, comment = "#>")
library(png)
library(grid)
library(gridExtra)
```

# cerUB tutorial {-}

Tutorial showcasing the cerUB package for R ([cerUB](https://github.com/Andros-Spica/cerUB)).

This document shows how to use *cerUB* protocols to explore petrographic and compositional data. As an example, we provide the 'amphorae' dataset concerning wine Roman amphorae from sites in Catalonia, NE Spain. It is a live version of the Appendix C of an article published in Journal of Archaeological Science (see reference below).

1. [Installing cerUB](#install)
2. [Initial procedures](#init)
3. [Protocol 1 - Geochemical data](#prot1)
4. [Protocol 2 - Petrographic data](#prot2)
5. [Protocol 3 - Geochemical and petrographic data](#prot3)
6. [Protocol 4 - Provenance data](#prot4)
7. [Protocol 4 - Provenance data with shipwrecks](#prot4_ship)
8. [Appendix: Interpreting biplots](#interp_biplots)

---

All rmarkdown (.Rmd) source files are available in the [repository](https://github.com/Andros-Spica/cerUB_tutorial).

There, the [publication appendices](https://github.com/Andros-Spica/cerUB_tutorial/tree/master/publication_appendices) folder contains alternative versions of the appendices (supplementary materials) of the related article:

> Angourakis, A., Martínez Ferreras, V., Torrano A., Gurt Esparraguera, J.M. (2018) Presenting multivariate statistical protocols in R using Roman wine amphorae productions in Catalonia, Spain. *Journal of Archaeological Science*, 93:150-165. https://doi.org/10.1016/j.jas.2018.03.007

Additionaly, the repository also contains:
- [Poster](https://github.com/Andros-Spica/cerUB_tutorial/blob/master/poster_ISA2018/ISA2018_Angourakis_et_al.pdf) presented in the International Symposium on Archaeometry (ISA) in Merida, Mexico, May 2018.
- [Poster](https://github.com/Andros-Spica/cerUB_tutorial/tree/master/poster_OpenScienceHumanities2018/OSH2018_Angourakis_et_al.pdf) presented in the Open Science and The Humanities Conference in Barcelona, Spain, June 2018.

Please, address any issues, suggestions, and comments to Andreas Angourakis (andros.spica@gmail.com, or through *GitHub*, user **Andros-Spica**)